Search.appendIndex(
    [
                {
            "fqsen": "\\validacionFormularios",
            "name": "validacionFormularios",
            "summary": "Clase\u0020de\u0020validacion\u0020de\u0020formularios",
            "url": "classes/validacionFormularios.html"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AcomprobarAlfabetico\u0028\u0029",
            "name": "comprobarAlfabetico",
            "summary": "Funcion\u0020comprobarAlfabetico",
            "url": "classes/validacionFormularios.html#method_comprobarAlfabetico"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AcomprobarAlfaNumerico\u0028\u0029",
            "name": "comprobarAlfaNumerico",
            "summary": "Funcion\u0020comprobarAlfaNumerico",
            "url": "classes/validacionFormularios.html#method_comprobarAlfaNumerico"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AcomprobarEntero\u0028\u0029",
            "name": "comprobarEntero",
            "summary": "Funcion\u0020comprobarEntero",
            "url": "classes/validacionFormularios.html#method_comprobarEntero"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AcomprobarFloat\u0028\u0029",
            "name": "comprobarFloat",
            "summary": "Funcion\u0020comprobarFloat",
            "url": "classes/validacionFormularios.html#method_comprobarFloat"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AvalidarEmail\u0028\u0029",
            "name": "validarEmail",
            "summary": "Funcion\u0020validarEmail",
            "url": "classes/validacionFormularios.html#method_validarEmail"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AvalidarURL\u0028\u0029",
            "name": "validarURL",
            "summary": "Funcion\u0020validarURL",
            "url": "classes/validacionFormularios.html#method_validarURL"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AvalidarFecha\u0028\u0029",
            "name": "validarFecha",
            "summary": "Funcion\u0020validarFecha",
            "url": "classes/validacionFormularios.html#method_validarFecha"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AvalidarDni\u0028\u0029",
            "name": "validarDni",
            "summary": "Funcion\u0020validarDni",
            "url": "classes/validacionFormularios.html#method_validarDni"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AvalidarCp\u0028\u0029",
            "name": "validarCp",
            "summary": "Funcion\u0020validarFecha",
            "url": "classes/validacionFormularios.html#method_validarCp"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AvalidarPassword\u0028\u0029",
            "name": "validarPassword",
            "summary": "Funcion\u0020validarPassword",
            "url": "classes/validacionFormularios.html#method_validarPassword"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AcomprobarNoVacio\u0028\u0029",
            "name": "comprobarNoVacio",
            "summary": "Funcion\u0020comprobarNoVacio",
            "url": "classes/validacionFormularios.html#method_comprobarNoVacio"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AcomprobarMaxTamanio\u0028\u0029",
            "name": "comprobarMaxTamanio",
            "summary": "Funcion\u0020comprobarMaxTamanio",
            "url": "classes/validacionFormularios.html#method_comprobarMaxTamanio"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AcomprobarMinTamanio\u0028\u0029",
            "name": "comprobarMinTamanio",
            "summary": "Funcion\u0020comprobarMinTamanio",
            "url": "classes/validacionFormularios.html#method_comprobarMinTamanio"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AvalidarElementoEnLista\u0028\u0029",
            "name": "validarElementoEnLista",
            "summary": "Funcion\u0020validarElementoEnLista",
            "url": "classes/validacionFormularios.html#method_validarElementoEnLista"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AvalidarTelefono\u0028\u0029",
            "name": "validarTelefono",
            "summary": "Funcion\u0020validarTelefono",
            "url": "classes/validacionFormularios.html#method_validarTelefono"
        },                {
            "fqsen": "\\DBPDO",
            "name": "DBPDO",
            "summary": "Class\u0020DBPDO",
            "url": "classes/DBPDO.html"
        },                {
            "fqsen": "\\DBPDO\u003A\u003AejecutaConsulta\u0028\u0029",
            "name": "ejecutaConsulta",
            "summary": "funcion\u0020ejecutarConsulta\u0020usada\u0020para\u0020lanzar\u0020todas\u0020las\u0020consultas\u0020necesitas\u0020contra\u0020la\u0020base\u0020de\u0020datos\u0020de\u0020forma\u0020instanciada\u0020y\u0020segura",
            "url": "classes/DBPDO.html#method_ejecutaConsulta"
        },                {
            "fqsen": "\\Usuario",
            "name": "Usuario",
            "summary": "Class\u0020Usuario",
            "url": "classes/Usuario.html"
        },                {
            "fqsen": "\\Usuario\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Instaciamos\u0020el\u0020objeto\u0020de\u0020clase\u0020Usuario",
            "url": "classes/Usuario.html#method___construct"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetCodUsuario\u0028\u0029",
            "name": "getCodUsuario",
            "summary": "Devuelve\u0020el\u0020valor\u0020de\u0020los\u0020atributos",
            "url": "classes/Usuario.html#method_getCodUsuario"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetPassword\u0028\u0029",
            "name": "getPassword",
            "summary": "",
            "url": "classes/Usuario.html#method_getPassword"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetDescUsuario\u0028\u0029",
            "name": "getDescUsuario",
            "summary": "",
            "url": "classes/Usuario.html#method_getDescUsuario"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetNumAccesos\u0028\u0029",
            "name": "getNumAccesos",
            "summary": "",
            "url": "classes/Usuario.html#method_getNumAccesos"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetFechaHoraUltimaConexion\u0028\u0029",
            "name": "getFechaHoraUltimaConexion",
            "summary": "",
            "url": "classes/Usuario.html#method_getFechaHoraUltimaConexion"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetPerfil\u0028\u0029",
            "name": "getPerfil",
            "summary": "",
            "url": "classes/Usuario.html#method_getPerfil"
        },                {
            "fqsen": "\\Usuario\u003A\u003AsetCodUsuario\u0028\u0029",
            "name": "setCodUsuario",
            "summary": "Cambia\u0020el\u0020valor\u0020de\u0020los\u0020atributos",
            "url": "classes/Usuario.html#method_setCodUsuario"
        },                {
            "fqsen": "\\Usuario\u003A\u003AsetPassword\u0028\u0029",
            "name": "setPassword",
            "summary": "",
            "url": "classes/Usuario.html#method_setPassword"
        },                {
            "fqsen": "\\Usuario\u003A\u003AsetDescUsuario\u0028\u0029",
            "name": "setDescUsuario",
            "summary": "",
            "url": "classes/Usuario.html#method_setDescUsuario"
        },                {
            "fqsen": "\\Usuario\u003A\u003AsetNumAccesos\u0028\u0029",
            "name": "setNumAccesos",
            "summary": "",
            "url": "classes/Usuario.html#method_setNumAccesos"
        },                {
            "fqsen": "\\Usuario\u003A\u003AsetFechaHoraUltimaConexion\u0028\u0029",
            "name": "setFechaHoraUltimaConexion",
            "summary": "",
            "url": "classes/Usuario.html#method_setFechaHoraUltimaConexion"
        },                {
            "fqsen": "\\Usuario\u003A\u003AsetPerfil\u0028\u0029",
            "name": "setPerfil",
            "summary": "",
            "url": "classes/Usuario.html#method_setPerfil"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024codUsuario",
            "name": "codUsuario",
            "summary": "",
            "url": "classes/Usuario.html#property_codUsuario"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024password",
            "name": "password",
            "summary": "",
            "url": "classes/Usuario.html#property_password"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024descUsuario",
            "name": "descUsuario",
            "summary": "",
            "url": "classes/Usuario.html#property_descUsuario"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024numAccesos",
            "name": "numAccesos",
            "summary": "",
            "url": "classes/Usuario.html#property_numAccesos"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024fechaHoraUltimaConexion",
            "name": "fechaHoraUltimaConexion",
            "summary": "",
            "url": "classes/Usuario.html#property_fechaHoraUltimaConexion"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024perfil",
            "name": "perfil",
            "summary": "",
            "url": "classes/Usuario.html#property_perfil"
        },                {
            "fqsen": "\\UsuarioPDO",
            "name": "UsuarioPDO",
            "summary": "Class\u0020UsuarioPDO",
            "url": "classes/UsuarioPDO.html"
        },                {
            "fqsen": "\\UsuarioPDO\u003A\u003AvalidarUsuario\u0028\u0029",
            "name": "validarUsuario",
            "summary": "funcion\u0020validarUsuario\u0020\u003A\u0020Comprueba\u0020si\u0020el\u0020usuario\u0020ha\u0020insertado\u0020correctamente\u0020las\u0020credenciales\u0020insertadas",
            "url": "classes/UsuarioPDO.html#method_validarUsuario"
        },                {
            "fqsen": "\\UsuarioPDO\u003A\u003AvalidarCodNoExiste\u0028\u0029",
            "name": "validarCodNoExiste",
            "summary": "funcion\u0020validarCodNoExiste\u0020\u003A\u0020Comprueba\u0020si\u0020el\u0020usuario\u0020ha\u0020insertado\u0020existe\u0020dentro\u0020de\u0020la\u0020base\u0020de\u0020datos\u0020en\u0020caso\u0020positivo\u0020devuelve\u0020el\u0020mensaje\u0020de\u0020error",
            "url": "classes/UsuarioPDO.html#method_validarCodNoExiste"
        },                {
            "fqsen": "\\UsuarioPDO\u003A\u003AaltaUsuario\u0028\u0029",
            "name": "altaUsuario",
            "summary": "funcion\u0020altaUsuario\u003A\u0020A\u00F1ade\u0020un\u0020nuevo\u0020usuario\u0020a\u0020la\u0020base\u0020de\u0020datos\u0020con\u0020los\u0020atributos\u0020recibidos\u0020por\u0020el\u0020formulario",
            "url": "classes/UsuarioPDO.html#method_altaUsuario"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
