Search.appendIndex(
    [
                {
            "fqsen": "\\validacionFormularios",
            "name": "validacionFormularios",
            "summary": "Clase\u0020de\u0020validacion\u0020de\u0020formularios",
            "url": "classes/validacionFormularios.html"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AcomprobarAlfabetico\u0028\u0029",
            "name": "comprobarAlfabetico",
            "summary": "Funcion\u0020comprobarAlfabetico",
            "url": "classes/validacionFormularios.html#method_comprobarAlfabetico"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AcomprobarAlfaNumerico\u0028\u0029",
            "name": "comprobarAlfaNumerico",
            "summary": "Funcion\u0020comprobarAlfaNumerico",
            "url": "classes/validacionFormularios.html#method_comprobarAlfaNumerico"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AcomprobarEntero\u0028\u0029",
            "name": "comprobarEntero",
            "summary": "Funcion\u0020comprobarEntero",
            "url": "classes/validacionFormularios.html#method_comprobarEntero"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AcomprobarFloat\u0028\u0029",
            "name": "comprobarFloat",
            "summary": "Funcion\u0020comprobarFloat",
            "url": "classes/validacionFormularios.html#method_comprobarFloat"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AvalidarEmail\u0028\u0029",
            "name": "validarEmail",
            "summary": "Funcion\u0020validarEmail",
            "url": "classes/validacionFormularios.html#method_validarEmail"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AvalidarURL\u0028\u0029",
            "name": "validarURL",
            "summary": "Funcion\u0020validarURL",
            "url": "classes/validacionFormularios.html#method_validarURL"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AvalidarFecha\u0028\u0029",
            "name": "validarFecha",
            "summary": "Funcion\u0020validarFecha",
            "url": "classes/validacionFormularios.html#method_validarFecha"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AvalidarDni\u0028\u0029",
            "name": "validarDni",
            "summary": "Funcion\u0020validarDni",
            "url": "classes/validacionFormularios.html#method_validarDni"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AvalidarCp\u0028\u0029",
            "name": "validarCp",
            "summary": "Funcion\u0020validarFecha",
            "url": "classes/validacionFormularios.html#method_validarCp"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AvalidarPassword\u0028\u0029",
            "name": "validarPassword",
            "summary": "Funcion\u0020validarPassword",
            "url": "classes/validacionFormularios.html#method_validarPassword"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AcomprobarNoVacio\u0028\u0029",
            "name": "comprobarNoVacio",
            "summary": "Funcion\u0020comprobarNoVacio",
            "url": "classes/validacionFormularios.html#method_comprobarNoVacio"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AcomprobarMaxTamanio\u0028\u0029",
            "name": "comprobarMaxTamanio",
            "summary": "Funcion\u0020comprobarMaxTamanio",
            "url": "classes/validacionFormularios.html#method_comprobarMaxTamanio"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AcomprobarMinTamanio\u0028\u0029",
            "name": "comprobarMinTamanio",
            "summary": "Funcion\u0020comprobarMinTamanio",
            "url": "classes/validacionFormularios.html#method_comprobarMinTamanio"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AvalidarElementoEnLista\u0028\u0029",
            "name": "validarElementoEnLista",
            "summary": "Funcion\u0020validarElementoEnLista",
            "url": "classes/validacionFormularios.html#method_validarElementoEnLista"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AvalidarTelefono\u0028\u0029",
            "name": "validarTelefono",
            "summary": "Funcion\u0020validarTelefono",
            "url": "classes/validacionFormularios.html#method_validarTelefono"
        },                {
            "fqsen": "\\DBPDO",
            "name": "DBPDO",
            "summary": "Class\u0020DBPDO",
            "url": "classes/DBPDO.html"
        },                {
            "fqsen": "\\DBPDO\u003A\u003AejecutaConsulta\u0028\u0029",
            "name": "ejecutaConsulta",
            "summary": "funcion\u0020ejecutarConsulta\u0020usada\u0020para\u0020lanzar\u0020todas\u0020las\u0020consultas\u0020necesitas\u0020contra\u0020la\u0020base\u0020de\u0020datos\u0020de\u0020forma\u0020instanciada\u0020y\u0020segura",
            "url": "classes/DBPDO.html#method_ejecutaConsulta"
        },                {
            "fqsen": "\\REST",
            "name": "REST",
            "summary": "",
            "url": "classes/REST.html"
        },                {
            "fqsen": "\\REST\u003A\u003AsevicioAPOD\u0028\u0029",
            "name": "sevicioAPOD",
            "summary": "Llama\u0020al\u0020servicio\u0020API\u0020REST\u0020APOD\u0028Astronomy\u0020Picture\u0020of\u0020the\u0020Day\u0029,\u0020que\u0020nos\u0020devuelve\u0020la\u0020imagen\u0020atron\u00F3mica\u0020del\nd\u00EDa\u0020e\u0020informaci\u00F3n\u0020relativa\u0020a\u0020esta.",
            "url": "classes/REST.html#method_sevicioAPOD"
        },                {
            "fqsen": "\\REST\u003A\u003AservicioIPGEO\u0028\u0029",
            "name": "servicioIPGEO",
            "summary": "Llama\u0020al\u0020servicio\u0020API\u0020REST\u0020apigeolocation,\u0020que\u0020nos\u0020devuelve\u0020la\u0020geolocalizaci\u00F3n\u0020de\u0020la\u0020ip\u0020enviada",
            "url": "classes/REST.html#method_servicioIPGEO"
        },                {
            "fqsen": "\\Usuario",
            "name": "Usuario",
            "summary": "Class\u0020Usuario",
            "url": "classes/Usuario.html"
        },                {
            "fqsen": "\\Usuario\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Instaciamos\u0020el\u0020objeto\u0020de\u0020clase\u0020Usuario",
            "url": "classes/Usuario.html#method___construct"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetCodUsuario\u0028\u0029",
            "name": "getCodUsuario",
            "summary": "Devuelve\u0020el\u0020valor\u0020de\u0020los\u0020atributos",
            "url": "classes/Usuario.html#method_getCodUsuario"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetPassword\u0028\u0029",
            "name": "getPassword",
            "summary": "",
            "url": "classes/Usuario.html#method_getPassword"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetDescUsuario\u0028\u0029",
            "name": "getDescUsuario",
            "summary": "",
            "url": "classes/Usuario.html#method_getDescUsuario"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetNumAccesos\u0028\u0029",
            "name": "getNumAccesos",
            "summary": "",
            "url": "classes/Usuario.html#method_getNumAccesos"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetFechaHoraUltimaConexion\u0028\u0029",
            "name": "getFechaHoraUltimaConexion",
            "summary": "",
            "url": "classes/Usuario.html#method_getFechaHoraUltimaConexion"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetPerfil\u0028\u0029",
            "name": "getPerfil",
            "summary": "",
            "url": "classes/Usuario.html#method_getPerfil"
        },                {
            "fqsen": "\\Usuario\u003A\u003AsetCodUsuario\u0028\u0029",
            "name": "setCodUsuario",
            "summary": "Cambia\u0020el\u0020valor\u0020de\u0020los\u0020atributos",
            "url": "classes/Usuario.html#method_setCodUsuario"
        },                {
            "fqsen": "\\Usuario\u003A\u003AsetPassword\u0028\u0029",
            "name": "setPassword",
            "summary": "",
            "url": "classes/Usuario.html#method_setPassword"
        },                {
            "fqsen": "\\Usuario\u003A\u003AsetDescUsuario\u0028\u0029",
            "name": "setDescUsuario",
            "summary": "",
            "url": "classes/Usuario.html#method_setDescUsuario"
        },                {
            "fqsen": "\\Usuario\u003A\u003AsetNumAccesos\u0028\u0029",
            "name": "setNumAccesos",
            "summary": "",
            "url": "classes/Usuario.html#method_setNumAccesos"
        },                {
            "fqsen": "\\Usuario\u003A\u003AsetFechaHoraUltimaConexion\u0028\u0029",
            "name": "setFechaHoraUltimaConexion",
            "summary": "",
            "url": "classes/Usuario.html#method_setFechaHoraUltimaConexion"
        },                {
            "fqsen": "\\Usuario\u003A\u003AsetPerfil\u0028\u0029",
            "name": "setPerfil",
            "summary": "",
            "url": "classes/Usuario.html#method_setPerfil"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024codUsuario",
            "name": "codUsuario",
            "summary": "",
            "url": "classes/Usuario.html#property_codUsuario"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024password",
            "name": "password",
            "summary": "",
            "url": "classes/Usuario.html#property_password"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024descUsuario",
            "name": "descUsuario",
            "summary": "",
            "url": "classes/Usuario.html#property_descUsuario"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024numAccesos",
            "name": "numAccesos",
            "summary": "",
            "url": "classes/Usuario.html#property_numAccesos"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024fechaHoraUltimaConexion",
            "name": "fechaHoraUltimaConexion",
            "summary": "",
            "url": "classes/Usuario.html#property_fechaHoraUltimaConexion"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024perfil",
            "name": "perfil",
            "summary": "",
            "url": "classes/Usuario.html#property_perfil"
        },                {
            "fqsen": "\\UsuarioPDO",
            "name": "UsuarioPDO",
            "summary": "Class\u0020UsuarioPDO",
            "url": "classes/UsuarioPDO.html"
        },                {
            "fqsen": "\\UsuarioPDO\u003A\u003AvalidarUsuario\u0028\u0029",
            "name": "validarUsuario",
            "summary": "funcion\u0020validarUsuario\u0020\u003A\u0020Comprueba\u0020si\u0020el\u0020usuario\u0020ha\u0020insertado\u0020correctamente\u0020las\u0020credenciales\u0020insertadas",
            "url": "classes/UsuarioPDO.html#method_validarUsuario"
        },                {
            "fqsen": "\\UsuarioPDO\u003A\u003AvalidarCodNoExiste\u0028\u0029",
            "name": "validarCodNoExiste",
            "summary": "funcion\u0020validarCodNoExiste\u0020\u003A\u0020Comprueba\u0020si\u0020el\u0020usuario\u0020ha\u0020insertado\u0020existe\u0020dentro\u0020de\u0020la\u0020base\u0020de\u0020datos\u0020en\u0020caso\u0020positivo\u0020devuelve\u0020el\u0020mensaje\u0020de\u0020error",
            "url": "classes/UsuarioPDO.html#method_validarCodNoExiste"
        },                {
            "fqsen": "\\UsuarioPDO\u003A\u003AaltaUsuario\u0028\u0029",
            "name": "altaUsuario",
            "summary": "funcion\u0020altaUsuario\u003A\u0020A\u00F1ade\u0020un\u0020nuevo\u0020usuario\u0020a\u0020la\u0020base\u0020de\u0020datos\u0020con\u0020los\u0020atributos\u0020recibidos\u0020por\u0020el\u0020formulario",
            "url": "classes/UsuarioPDO.html#method_altaUsuario"
        },                {
            "fqsen": "\\UsuarioPDO\u003A\u003AmodificarUsuario\u0028\u0029",
            "name": "modificarUsuario",
            "summary": "funcion\u0020modificarUsuario\u003A\u0020Modificamos\u0020la\u0020descripcion\u0020del\u0020usuario",
            "url": "classes/UsuarioPDO.html#method_modificarUsuario"
        },                {
            "fqsen": "\\UsuarioPDO\u003A\u003AborrarUsuario\u0028\u0029",
            "name": "borrarUsuario",
            "summary": "funcion\u0020borrarUsuario\u003A\u0020borramos\u0020el\u0020usuario\u0020logeado",
            "url": "classes/UsuarioPDO.html#method_borrarUsuario"
        },                {
            "fqsen": "\\UsuarioPDO\u003A\u003AconsultarUsuario\u0028\u0029",
            "name": "consultarUsuario",
            "summary": "",
            "url": "classes/UsuarioPDO.html#method_consultarUsuario"
        },                {
            "fqsen": "\\Departamento",
            "name": "Departamento",
            "summary": "Class\u0020Departamentos",
            "url": "classes/Departamento.html"
        },                {
            "fqsen": "\\Departamento\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Instancia\u0020un\u0020objeto\u0020de\u0020la\u0020clase\u0020Departamento",
            "url": "classes/Departamento.html#method___construct"
        },                {
            "fqsen": "\\Departamento\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "Devuelve\u0020el\u0020valor\u0020de\u0020un\u0020atributo",
            "url": "classes/Departamento.html#method___get"
        },                {
            "fqsen": "\\Departamento\u003A\u003A__set\u0028\u0029",
            "name": "__set",
            "summary": "Cambia\u0020el\u0020valor\u0020de\u0020un\u0020atributo",
            "url": "classes/Departamento.html#method___set"
        },                {
            "fqsen": "\\Departamento\u003A\u003A\u0024codDepartamento",
            "name": "codDepartamento",
            "summary": "",
            "url": "classes/Departamento.html#property_codDepartamento"
        },                {
            "fqsen": "\\Departamento\u003A\u003A\u0024descDepartamento",
            "name": "descDepartamento",
            "summary": "",
            "url": "classes/Departamento.html#property_descDepartamento"
        },                {
            "fqsen": "\\Departamento\u003A\u003A\u0024volumenDeNegocio",
            "name": "volumenDeNegocio",
            "summary": "",
            "url": "classes/Departamento.html#property_volumenDeNegocio"
        },                {
            "fqsen": "\\Departamento\u003A\u003A\u0024fechaCreacionDepartamento",
            "name": "fechaCreacionDepartamento",
            "summary": "",
            "url": "classes/Departamento.html#property_fechaCreacionDepartamento"
        },                {
            "fqsen": "\\Departamento\u003A\u003A\u0024fechaBajaDepartamento",
            "name": "fechaBajaDepartamento",
            "summary": "",
            "url": "classes/Departamento.html#property_fechaBajaDepartamento"
        },                {
            "fqsen": "\\DepartamentoPDO",
            "name": "DepartamentoPDO",
            "summary": "Class\u0020DepartamentoPDO",
            "url": "classes/DepartamentoPDO.html"
        },                {
            "fqsen": "\\DepartamentoPDO\u003A\u003AbuscaDepartamentosPorDescripcion\u0028\u0029",
            "name": "buscaDepartamentosPorDescripcion",
            "summary": "funcion\u0020buscaDepartamentosPorDescripcion\u0020\u003A\u0020Busca\u0020todos\u0020los\u0020departamentos\u0020si\u0020hay\u0020con\u0020la\u0020descripcion\u0020total\u0020o\u0020parcial\u0020de\u0020este",
            "url": "classes/DepartamentoPDO.html#method_buscaDepartamentosPorDescripcion"
        },                {
            "fqsen": "\\DepartamentoPDO\u003A\u003AbuscaDepartamentosPorCodigo\u0028\u0029",
            "name": "buscaDepartamentosPorCodigo",
            "summary": "funcion\u0020buscaDepartamentosPorCodigo\u0020\u003A\u0020Busca\u0020coincidencia\u0020por\u0020el\u0020codigo\u0020de\u0020departamento",
            "url": "classes/DepartamentoPDO.html#method_buscaDepartamentosPorCodigo"
        },                {
            "fqsen": "\\DepartamentoPDO\u003A\u003AaltaDepartamento\u0028\u0029",
            "name": "altaDepartamento",
            "summary": "funcion\u0020altaDepartamento\u0020\u003A\u0020a\u00F1ade\u0020un\u0020nuevo\u0020departamento\u0020a\u0020la\u0020base\u0020de\u0020datos",
            "url": "classes/DepartamentoPDO.html#method_altaDepartamento"
        },                {
            "fqsen": "\\DepartamentoPDO\u003A\u003AbajaFisicaDepartamento\u0028\u0029",
            "name": "bajaFisicaDepartamento",
            "summary": "funcion\u0020bajaFisicaDepartamento\u0020\u003A\u0020borra\u0020el\u0020departamento\u0020de\u0020la\u0020base\u0020de\u0020datos",
            "url": "classes/DepartamentoPDO.html#method_bajaFisicaDepartamento"
        },                {
            "fqsen": "\\DepartamentoPDO\u003A\u003AbajaLogicaDepartamento\u0028\u0029",
            "name": "bajaLogicaDepartamento",
            "summary": "funcion\u0020bajaLogicaDepartamento\u0020\u003A\u0020modifica\u0020la\u0020tupla\u0020de\u0020fechaBaja\u0020para\u0020dar\u0020de\u0020baja\u0020logica\u0020al\u0020departamento",
            "url": "classes/DepartamentoPDO.html#method_bajaLogicaDepartamento"
        },                {
            "fqsen": "\\DepartamentoPDO\u003A\u003AaltaLogicaDepartamento\u0028\u0029",
            "name": "altaLogicaDepartamento",
            "summary": "funcion\u0020altaLogicaDepartamento\u0020\u003A\u0020modifica\u0020la\u0020tupla\u0020de\u0020fechaBaja\u0020a\u0020null\u0020para\u0020reabilitar\u0020el\u0020departamento",
            "url": "classes/DepartamentoPDO.html#method_altaLogicaDepartamento"
        },                {
            "fqsen": "\\DepartamentoPDO\u003A\u003AobtenerDatosDepartamento\u0028\u0029",
            "name": "obtenerDatosDepartamento",
            "summary": "funcion\u0020obtenerDatosDepartamento\u0020\u003Aobtine\u0020los\u0020datos\u0020del\u0020departamento\u0020atraves\u0020del\u0020codigo\u0020de\u0020departamento",
            "url": "classes/DepartamentoPDO.html#method_obtenerDatosDepartamento"
        },                {
            "fqsen": "\\DepartamentoPDO\u003A\u003AmodificaDepartamento\u0028\u0029",
            "name": "modificaDepartamento",
            "summary": "funcion\u0020altaLogicaDepartamento\u0020\u003A\u0020modifica\u0020la\u0020tupla\u0020de\u0020fechaBaja\u0020a\u0020null\u0020para\u0020reabilitar\u0020el\u0020departamento",
            "url": "classes/DepartamentoPDO.html#method_modificaDepartamento"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
